- name: Install kubectl
  package:
    name: kubectl
    state: present
  vars:
    ansible_pkg_mgr_skip: yes
  register: k8s
  when: ansible_pkg_mgr == 'pacman'

- name: Install kubeadm
  package:
    name: kubeadm
    state: present
  vars:
    ansible_pkg_mgr_skip: yes
  when: ansible_pkg_mgr == 'pacman' and k8s['changed']