- name: Install Arch WSL2 Setup
  hosts: localhost
  gather_facts: true
  become: yes
  vars:
    user: "carlinhos"
    asdf_plugins: 
      - golang
      - python
      - erlang
      - rust
      - ruby

  tasks:
    - name: Install yay
      ansible.builtin.include_tasks:
        file: tasks/yay.yaml

    - name: Install unzip
      package:
        name: unzip
        state: present
      vars:
        ansible_pkg_mgr_skip: yes
      when: ansible_pkg_mgr == 'pacman'

    - name: Install Docker
      ansible.builtin.include_tasks:
        file: tasks/docker.yaml

    - name: Install ZSH
      ansible.builtin.include_tasks:
        file: tasks/zsh.yaml

    - name: Install asdf and langs
      ansible.builtin.include_tasks:
        file: tasks/asdf.yaml

    - name: Install Kubernetes
      ansible.builtin.include_tasks:
        file: tasks/kubernetes.yaml

    - name: Install Terraform
      package:
        name: terraform
        state: present
      vars:
        ansible_pkg_mgr_skip: yes
      when: ansible_pkg_mgr == 'pacman'

    - name: Install Bat
      package:
        name: bat
        state: present
      vars:
        ansible_pkg_mgr_skip: yes
      when: ansible_pkg_mgr == 'pacman'
    
    - name: Install Exa
      package:
        name: exa
        state: present
      vars:
        ansible_pkg_mgr_skip: yes
      when: ansible_pkg_mgr == 'pacman'

    - name: Install Github CLI
      package:
        name: github-cli
        state: present
      vars:
        ansible_pkg_mgr_skip: yes
      when: ansible_pkg_mgr == 'pacman'

    - name: Install Neovim
      ansible.builtin.include_tasks:
        file: tasks/neovim.yaml

    - name: Install GCloud CLI
      command: "yay -S --noconfirm google-cloud-cli"
      become_user: "{{ user }}"

    - name: Install Tmux
      ansible.builtin.include_tasks:
        file: tasks/tmux.yaml
