- name: Install Arch WSL2 Setup
  hosts: localhost
  gather_facts: true
  become: yes
  vars:
    user: "carlinhos"
    asdf_plugins: 
      - nodejs
      - golang
      - python
      - erlang
      - elixir
      - rust

  tasks:
    - name: Install yay
      ansible.builtin.include_tasks:
        file: tasks/yay.yaml

    - name: Install unzip
      command: "yay -S --noconfirm unzip"
      become_user: "{{ user }}"

    - name: Install Docker
      ansible.builtin.include_tasks:
        file: tasks/docker.yaml

    - name: Install ZSH
      ansible.builtin.include_tasks:
        file: tasks/zsh.yaml

    - name: Install asdf and langs
      ansible.builtin.include_tasks:
        file: tasks/asdf.yaml

    - name: Install Kubernetes
      ansible.builtin.include_tasks:
        file: tasks/kunernetes.yaml

    - name: Install Terraform
      command: "yay -S --noconfirm terraform"
      become_user: "{{ user }}"

    - name: Install Bat
      command: "yay -S --noconfirm bat"
      become_user: "{{ user }}"
    
    - name: Install Exa
      command: "yay -S --noconfirm exa"
      become_user: "{{ user }}"

    - name: Install Github CLI
      command: "yay -S --noconfirm github-cli"
      become_user: "{{ user }}"